/// ===========================================================================
/// Copyright (c) 2020-2023, BoxCat. All rights reserved.
/// Date: 2023-04-29 09:22:52
/// LastEditTime: 2023-05-02 18:56:02
/// FilePath: /lib/libs/img/srcat_pack.dart
/// ===========================================================================
// ignore_for_file: non_constant_identifier_names
// THIS FILE IS AUTOMATICALLY GENERATED! DO NOT EDIT BY HAND!

class SRCatImagePack {
  static String smile_hm_5_pack = "141a5f372e656979897bc3be01c54bf1";
  static String smile_hm_7_pack = "9a6b1d0ad1ced023da3ad7a3f7734e8a";
  static String character_small_1001 = "4f7e19e134ecc952225f5f5be962b098";
  static String character_small_1002 = "75c0f584c3d12612f87cfc32fbd6a52e";
  static String character_small_1003 = "7303bd456aea62f864877ada8b9ed99a";
  static String character_small_1004 = "10d14467d1897a169af4c18e9aa18373";
  static String character_small_1005 = "062978419c3b0149b5a69b0da8ee3723";
  static String character_small_1006 = "7ba119d74e58d9b3bf14443970925e69";
  static String character_small_1008 = "a636fcfff120096fd09dd61232e2bdbb";
  static String character_small_1009 = "26cebd0d70b860422aa5da8c1e24aef8";
  static String character_small_1013 = "cb967e1fe57a6c4a0da6a307f15ff654";
  static String character_small_1101 = "01750d3c79cf798c0ce928c9e9435fce";
  static String character_small_1102 = "a43445530180818e7dd89b710078d9ce";
  static String character_small_1103 = "ba3a11472e3395747b38761062b1a426";
  static String character_small_1104 = "4ecae61b7bed882417a0611252599041";
  static String character_small_1105 = "e777659ee1b379f79f29650f9bce891d";
  static String character_small_1106 = "5ec3cf602d840ae48662e1f9b0af2a2e";
  static String character_small_1107 = "3509f09ddf93a63ea3e23a2da265ef26";
  static String character_small_1108 = "237e3c9523bb6d21972b47c19f6ce0db";
  static String character_small_1109 = "0fd25e6c292192dbd1c92737a6499e12";
  static String character_small_1201 = "6b62d210672cc82a391fe972cd22ae99";
  static String character_small_1202 = "515a8877bb47c4a951a88c671492a477";
  static String character_small_1203 = "15751445fcdda32bcbaa34bcdb1b16cb";
  static String character_small_1204 = "ab59750527c43ff410cb49c02f40f82d";
  static String character_small_1205 = "21b882aabc518bf5daa761d2e125b212";
  static String character_small_1206 = "469a97796a9b8a0b11d0de121462b436";
  static String character_small_1207 = "077bf77ccfddafe9425b6e0f879536c6";
  static String character_small_1208 = "cb20b62d67517b7bd9d3e9951d9904a3";
  static String character_small_1209 = "39b7823247734db899f9fc790ffdb58f";
  static String character_small_1211 = "087d1d4cea6d88f584e3ad2d15ba7a30";
  static String character_small_1214 = "7ffbadb0f32e0cfe21490cad0628aa72";
  static String character_small_8001 = "c65ac7d8bb7ef9c84477a34460820dde";
  static String character_small_8002 = "5d4d9a04aa1ad4e5c63fe74acbfc8115";
  static String character_small_8003 = "d4435054392320a9ac6dcecc223a22d5";
  static String character_small_8004 = "9e5cac44e4cc1457c08661adbd477c50";
}
