name: srcat
description: "Honkai: Star Rail Toolbox on Windows"
publish_to: none

version: 0.2.0+12

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Fluent UI
  # https://pub.dev/packages/fluent_ui
  # https://pub.flutter-io.cn/packages/fluent_ui
  fluent_ui: ^4.7.0

  # System Theme
  # https://pub.dev/packages/system_theme
  # https://pub.flutter-io.cn/packages/system_theme
  system_theme: ^2.3.0
  
  # Fluent UI Icons
  # https://pub.dev/packages/fluentui_system_icons
  # https://pub.flutter-io.cn/packages/fluentui_system_icons
  fluentui_system_icons: ^1.1.205

  # flutter_acrylic
  # https://pub.dev/packages/flutter_acrylic
  # https://pub.flutter-io.cn/packages/flutter_acrylic
  flutter_acrylic: ^1.1.3

  # Flutter Riverpod
  # https://pub.dev/packages/flutter_riverpod
  # https://pub.flutter-io.cn/packages/flutter_riverpod
  flutter_riverpod: ^2.3.6

  # Go Router
  # https://pub.dev/packages/go_router
  # https://pub.flutter-io.cn/packages/go_router
  go_router: ^7.1.1

  # Url Launcher
  # https://pub.dev/packages/url_launcher
  # https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^6.1.12

  # Window Manager
  # https://pub.dev/packages/window_manager
  # https://pub.flutter-io.cn/packages/window_manager
  window_manager: ^0.3.5

  # i18n
  # https://pub.dev/packages/flutter_i18n
  # https://pub.flutter-io.cn/packages/flutter_i18n
  flutter_i18n: ^0.33.0

  # File Selector
  # https://pub.dev/packages/file_selector
  # https://pub.flutter-io.cn/packages/file_selector
  file_selector: ^1.0.0

  # File Provider
  # https://pub.dev/packages/path_provider
  # https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^2.0.15

  # WebView 2
  # https://pub.dev/packages/webview_windows
  # https://pub.flutter-io.cn/packages/webview_windows
  webview_windows:
    git:
      url: https://github.com/BakaLabs/flutter-webview-windows.git

  # SQLite
  # https://pub.dev/packages/sqflite
  # https://pub.flutter-io.cn/packages/sqflite
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5

  # Device Info
  # https://pub.dev/packages/device_info_plus
  # https://pub.flutter-io.cn/packages/device_info_plus
  device_info_plus:
    git:
      url: https://github.com/fluttercommunity/plus_plugins.git
      path: packages/device_info_plus/device_info_plus
      ref: main

  dyn_mouse_scroll: ^1.0.7

  package_info_plus: ^4.0.2

  ffi: ^2.0.2

  # Dio
  # https://pub.dev/packages/dio
  # https://pub.flutter-io.cn/packages/dio
  dio: ^5.2.1+1

  # Connectivity
  # https://pub.dev/packages/connectivity_plus
  # https://pub.flutter-io.cn/packages/connectivity_plus
  connectivity_plus: ^4.0.1

  # Chart
  # https://pub.dev/packages/fl_chart
  # https://pub.flutter-io.cn/packages/fl_chart
  fl_chart: ^0.63.0

  # win32 registry
  # https://pub.dev/packages/win32_registry
  # https://pub.flutter-io.cn/packages/win32_registry
  win32_registry: ^1.1.1

  convert: ^3.1.1

  flutter_widget_from_html_core: ^0.10.2

  sentry_flutter: ^7.8.0

  json_schema2: ^5.1.2+2

  crypto: ^3.0.3

  qr_flutter: ^4.1.0

  cupertino_icons: ^1.0.2

  # win32
  # https://pub.dev/packages/win32
  # https://pub.flutter-io.cn/packages/win32
  win32: ^5.0.5

dependency_overrides:
  # UUID
  # https://pub.dev/packages/uuid
  # https://pub.flutter-io.cn/packages/uuid
  uuid: ^4.0.0-beta3-1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  msix: ^3.12.2

flutter:
  uses-material-design: true

  fonts:
    - family: PingFang
      fonts:
        - asset: assets/fonts/PingFang-Bold.ttf
    - family: Cattie
      fonts:
        - asset: assets/fonts/Cattie-Regular.ttf
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf

  assets:
    - assets/i18n/
    - assets/images/
    - assets/images/srcat/
