/// ===========================================================================
/// Copyright (c) 2020-2023, BoxCat. All rights reserved.
/// Date: 2023-05-02 19:07:37
/// LastEditTime: 2023-05-02 19:14:24
/// FilePath: /lib/libs/sr/services/tools/warp/image.dart
/// ===========================================================================
// THIS FILE IS AUTOMATICALLY GENERATED! DO NOT EDIT BY HAND!

import 'package:srcat/libs/img/pak_loader.dart';

class SrWrapToolImageService {
  /// Avatar
  static List<Map<String, dynamic>> avatar = [
    { "id": 1001, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1001) },
    { "id": 1002, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1002) },
    { "id": 1003, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1003) },
    { "id": 1004, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1004) },
    { "id": 1005, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1005) },
    { "id": 1006, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1006) },
    { "id": 1008, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1008) },
    { "id": 1009, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1009) },
    { "id": 1013, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1013) },
    { "id": 1101, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1101) },
    { "id": 1102, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1102) },
    { "id": 1103, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1103) },
    { "id": 1104, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1104) },
    { "id": 1105, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1105) },
    { "id": 1106, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1106) },
    { "id": 1107, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1107) },
    { "id": 1108, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1108) },
    { "id": 1109, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1109) },
    { "id": 1201, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1201) },
    { "id": 1202, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1202) },
    { "id": 1203, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1203) },
    { "id": 1204, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1204) },
    { "id": 1205, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1205) },
    { "id": 1206, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1206) },
    { "id": 1207, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1207) },
    { "id": 1208, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1208) },
    { "id": 1209, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1209) },
    { "id": 1211, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1211) },
    { "id": 1214, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_1214) },
    { "id": 8001, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_8001) },
    { "id": 8002, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_8002) },
    { "id": 8003, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_8003) },
    { "id": 8004, "avatar": SRCatPackLoader.parse(SRCatImagePack.character_small_8004) }
  ];
}
